services:
  hydra:
    image: oryd/hydra:v2.2.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve all --dev
    environment:
      - SECRETS_SYSTEM=global_secret_to_encrypt_db
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=true
      - URLS_LOGIN=testDeepLink://mobile/login?path=login
      - URLS_CONSENT=testDeepLink://mobile/consent?path=consent
      # - URLS_LOGIN=http://localhost:3001/login?path=login
      # - URLS_CONSENT=http://localhost:3001/consent?path=consent
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - hydranet
  hydra-migrate:
    image: oryd/hydra:v2.2.0
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
    restart: on-failure
    networks:
      - hydranet
  postgresd:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - hydranet
  # app:
  #   build:
  #     context: ./server
  #   tty: true
  #   container_name: go-server
  #   volumes:
  #     - ../:/work/app
  #     - ~/.gitconfig:/root/.gitconfig
  #     - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
  #   working_dir: /work/app
  #   ports:
  #     - "8000:8000"

networks:
  hydranet:
